# Generated by Django 6.0.3 on 2026-03-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_customer_saleinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='computer.saleinvoice')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computer.productvariant')),
            ],
            options={
                'db_table': 'sale_invoice_detail',
                'ordering': ['id'],
            },
        ),
    ]
