# Generated by Django 6.0.3 on 2026-03-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_saleinvoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Khách lẻ'), ('customer', 'Khách hàng')], default='retail', max_length=20),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='computer.saleinvoice')),
            ],
            options={
                'db_table': 'sale_payment',
                'ordering': ['-date'],
            },
        ),
    ]
