# Generated by Django 6.0.3 on 2026-03-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_saleinvoice_paid_amount_saleinvoice_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='sale_type',
        ),
    ]
