# Generated by Django 6.0.3 on 2026-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Không giảm'), ('percent', 'Giảm theo %'), ('amount', 'Giảm theo tiền')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
